server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  name: "webpage_analyzer"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

logging:
  level: "info"
  format: "json"

analysis:
  timeout: 30
  max_content_size: 10485760  # 10MB
  user_agent: "WebPageAnalyzer/1.0"
