server:
  port: "8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: postgres
  port: "5432"
  user: postgres
  password: postgres
  name: webpage_analyzer
  ssl_mode: disable
  max_connections: 50
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  host: redis
  port: "6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s



logger:
  level: info
  development: false

analysis:
  request_timeout: 30s
  max_content_length: 10485760
  cache_ttl: 3600s
  rate_limit_per_ip: 100
  rate_limit_window: 1m
  max_concurrent_jobs: 50
  link_check_timeout: 5s
  max_links_to_check: 50
  max_concurrent_link_checks: 10
  max_html_depth: 100
  max_url_length: 2048
